lab8/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

lab8/mysite/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='home'),
    path('<int:cinema_id>/', views.detail, name='detail'),
]

lab8/mysite/shop/models.py
from django.db import models


class Cinema(models.Model):
    name = models.CharField(max_length=20)


class Description(models.Model):
    cinema_id = models.ForeignKey(Cinema, on_delete=models.CASCADE)
    description = models.CharField(max_length=1500)

lab8/mysite/shop/views.py
from django.shortcuts import get_object_or_404, render

from .models import Cinema
from .models import Description


def index(request):
    cinema_list = Cinema.objects.all()
    context = {'cinema_list': cinema_list}
    return render(request, 'shop/index.html', context)


def detail(request, cinema_id):
    cinema_list = Cinema.objects.all()
    for i in cinema_list:
        if i.id == cinema_id:
            cinema = i
    description = get_object_or_404(Description, pk=cinema_id)
    return render(request, 'shop/detail.html', {'cinema': cinema, 'description': description})

lab8/mysite/shop/templates/shop/detail.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>lab8</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <style>
      body{
        background-color:#212529;
        color:white;
      }
    </style>
</head>
<body class="d-flex h-100 text-center text-white bg-dark">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">CinemaPark</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}">Home</a>
      </nav>
    </div>
  </header>
    <main class="container-fluid bg-dark">
                <h1 class="text-center text-light">{{ cinema.name }}</h1>
                <table class="table table-dark table-borderless">
                    <tr>
                        <td class="text-light td-text-short" style="text-align: left">{{ description.description }}</td>
                        <td>
                            {% if cinema.id == 1 %}
                                <img  style="max-width: 250px; height: auto" src="{% static "shop/images/1.jpg" %}" alt="tenet" class="rounded img-fluid">
                            {% endif %}
                            {% if cinema.id == 2 %}
                                <img style="max-width: 300px; height: auto" src="{% static "shop/images/2.jpg" %}" alt="Interstellar" class="rounded img-fluid">
                            {% endif %}
                            {% if cinema.id == 3 %}
                                <img style="max-width: 150px; height: auto" src="{% static "shop/images/3.jpg" %}" alt="The Social Network" class="rounded img-fluid">
                            {% endif %}
                            {% if cinema.id == 4 %}
                                <img style="max-width: 250px; height: auto" src="{% static "shop/images/4.jpg" %}" alt="The Wolf of Wall Street" class="rounded img-fluid">
                            {% endif %}
                            {% if cinema.id == 5 %}
                                <img style="max-width: 300px; height: auto" src="{% static "shop/images/5.jpg" %}" alt="Snowden" class="rounded img-fluid">
                            {% endif %}
                        </td>
                    </tr>
                </table>
    </main>
    <footer class="high bg-dark">
    </footer>
</body>
</html>

lab8/mysite/shop/templates/shop/index.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>lab8</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
      body{
        background-color:#212529;
        color:white;
      }
    </style>
</head>
<body class="d-flex h-100 text-center text-white bg-dark">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">CinemaPark</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
      </nav>
    </div>
  </header>
    <main class="px-3">
                {% if cinema_list %}
                    <ul class="list-group">
                    {% for cinema in cinema_list %}
                    <li class="list-group-item">
                    <a class="nav-link list" href="{% url 'shop:detail' cinema.id %}">{{ cinema.name }}</a>
                    </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <p>No films are available.</p>
                {% endif %}
    </main>
  <footer class="mt-auto text-white-50">
    <p>ИУ5-54</p>
  </footer>
</div>
</body>
</html>